name: macOS

on:
  push:
    branches:
      - '*'
      - 'feature/*'
      - 'release/*'
      - 'bugfix/*'
    tags: '*'

jobs:
  build:
    env:
      PACKAGE_NAME: SyndiKit

    runs-on: macos-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"

    strategy:
      matrix:
        xcode: ["/Applications/Xcode_12.3.app", "/Applications/Xcode_12.4.app"]

    steps:
    - uses: actions/checkout@v2
    - name: Set Xcode Name
      run: echo "XCODE_NAME=$(basename -- ${{ matrix.xcode }} | sed 's/\.[^.]*$//' | cut -d'_' -f2)" >> $GITHUB_ENV
    - name: Setup Xcode
      run: sudo xcode-select -s ${{ matrix.xcode }}/Contents/Developer
    - name: Build
      run: swift build -v
    - name: Lint
      if: startsWith(github.ref, 'refs/tags/') != true
      run: swift run swiftformat --lint . && swift run swiftlint
    - name: Run tests
      run: swift test -v --enable-code-coverage
    - name: Prepare Code Coverage
      run: xcrun llvm-cov export -format="lcov" .build/debug/${{ env.PACKAGE_NAME }}PackageTests.xctest/Contents/MacOS/${{ env.PACKAGE_NAME }}PackageTests -instr-profile .build/debug/codecov/default.profdata > info.lcov
    - name: Upload to CodeCov.io
      run: bash <(curl https://codecov.io/bash) -F github -F macOS -F ${{ matrix.runs-on }}
      env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    - name: Build Documentation
      if: ${{ matrix.os == 'macos-11' && matrix.xcode == '/Applications/Xcode_12.5.app' && !startsWith(github.ref, 'refs/tags/') }}
      run: |
        swift run sourcedocs generate build -cra
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git status
        git add Documentation
        git diff-index --quiet HEAD || git commit -m "[github action] Update Docs"
        git push
